### ISSUE TITLE
Wungle text button does nothing on image-only posts

### ISSUE THREAD

**Issue by pyrogaming09-2** [samolukadjo/wungle-text-for-tumblr#10]
**Is your feature request related to a problem? Please describe.**
Yes, pressing the wungle text button on image-only posts doesn't change the button and generally does nothing.

**Describe the solution you'd like**
Remove the button on image-only posts

**Describe alternatives you've considered**
N/A

**Additional context**
omg haiiii im your tumblr moot dave-strider-is-my-bf

**Comment by samolukadjo** [comment]
Haiiiii! I will see about checking if a post has decodable elements before adding the button!

**Comment by samolukadjo** [comment]
This has been done in the latest version
